### ISSUE TITLE
More infomation about the board

### ISSUE THREAD

**Issue by motolav** [natedogg2020/Inland_ESP32-Supplements#1]
One of the Q&A responses got a response that the board was a rebranded KS0413 keyestudio ESP32 Core Board

Here's the link to the wiki page for it so people who stumble on this repo can get more documentation.
https://wiki.keyestudio.com/KS0413_keyestudio_ESP32_Core_Board

EDIT:
I just found a question on adding support for it on PlatformIO and the response was to use esp32dev as its the same pinout
https://github.com/platformio/platform-espressif32/issues/327

**Comment by NamShubEnki** [comment]
Thanks for the addition @motolav! I spent a number of days working to get things just right with this board, and the photos posted here were definitely a help. 

In reference to the pinout photos posted, would you be able to post the original file you gridded them on? I found myself needing to switch back and forth between this & the esp32 datasheet to check IO number vs pin number. 

[The Base ESP32 datasheet, contains pin master guide, definitions.](http://espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf)

[Datasheet for ESP32-WROOM-32D](https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32d_esp32-wroom-32u_datasheet_en.pdf)
